package ru.georgdeveloper.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JobDescriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescriptionAllPropertiesEquals(JobDescription expected, JobDescription actual) {
        assertJobDescriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertJobDescriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescriptionAllUpdatablePropertiesEquals(JobDescription expected, JobDescription actual) {
        assertJobDescriptionUpdatableFieldsEquals(expected, actual);
        assertJobDescriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescriptionAutoGeneratedPropertiesEquals(JobDescription expected, JobDescription actual) {
        assertThat(actual)
            .as("Verify JobDescription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescriptionUpdatableFieldsEquals(JobDescription expected, JobDescription actual) {
        assertThat(actual)
            .as("Verify JobDescription relevant properties")
            .satisfies(a -> assertThat(a.getDescriptionName()).as("check descriptionName").isEqualTo(expected.getDescriptionName()))
            .satisfies(a -> assertThat(a.getApprovalDate()).as("check approvalDate").isEqualTo(expected.getApprovalDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescriptionUpdatableRelationshipsEquals(JobDescription expected, JobDescription actual) {
        // empty method
    }
}
