package ru.georgdeveloper.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionAllPropertiesEquals(Profession expected, Profession actual) {
        assertProfessionAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionAllUpdatablePropertiesEquals(Profession expected, Profession actual) {
        assertProfessionUpdatableFieldsEquals(expected, actual);
        assertProfessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionAutoGeneratedPropertiesEquals(Profession expected, Profession actual) {
        assertThat(actual)
            .as("Verify Profession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionUpdatableFieldsEquals(Profession expected, Profession actual) {
        assertThat(actual)
            .as("Verify Profession relevant properties")
            .satisfies(a -> assertThat(a.getProfessionName()).as("check professionName").isEqualTo(expected.getProfessionName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionUpdatableRelationshipsEquals(Profession expected, Profession actual) {
        assertThat(actual)
            .as("Verify Profession relationships")
            .satisfies(a -> assertThat(a.getEmployees()).as("check employees").isEqualTo(expected.getEmployees()));
    }
}
